"""The words a new household is seeded with, and their translations (#268).

A household starts with a category tree and, once an account is opened with a
balance, an "Opening balance" payee. Both are ordinary data from the moment
they are written: a person renames them like anything they typed, and nothing
stores which language they were seeded in.

Each word has a stable id here and the same id in the client's catalogs
(`client/src/lib/seedWords.ts`), so a translator meets it in the `.po` file
beside every other message. The server cannot read those catalogs at run time
-- the image carries the built client, not its sources -- so
`app/seed_catalog.json` holds what it needs from them: **reviewed
translations only**, generated by `scripts/seed_catalog.py`. A draft (`#,
fuzzy`) is never seeded, for the same reason the client never serves one, so
until #58 reviews a language every household is seeded in English whatever is
asked for.

`tests/test_seed_words.py` holds the three together: the ids and English here
equal the client's, and the JSON is what the script would write today.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

#: Where the reviewed translations live, as ``{locale: {id: text}}``.
CATALOG_PATH = Path(__file__).with_name("seed_catalog.json")

#: A BCP 47 tag, loosely: enough to refuse anything that is not one before it
#: is used as a key. An unknown but well-formed tag simply seeds English.
LOCALE_TAG = re.compile(r"[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8}){0,3}")

OPENING_BALANCE = "seed.opening_balance"

#: id -> English. The English is byte for byte what households were seeded with
#: before this module existed.
ENGLISH: dict[str, str] = {
    OPENING_BALANCE: "Opening balance",
    "seed.group.income": "Income",
    "seed.category.salary": "Salary",
    "seed.category.other_income": "Other Income",
    "seed.group.bills": "Bills",
    "seed.category.rent_mortgage": "Rent / Mortgage",
    "seed.category.electricity": "Electricity",
    "seed.category.water": "Water",
    "seed.category.internet": "Internet",
    "seed.category.phone": "Phone",
    "seed.category.insurance": "Insurance",
    "seed.group.everyday": "Everyday",
    "seed.category.groceries": "Groceries",
    "seed.category.eating_out": "Eating Out",
    "seed.category.transport": "Transport",
    "seed.category.household": "Household",
    "seed.category.health": "Health",
    "seed.group.quality_of_life": "Quality of Life",
    "seed.category.travel": "Travel",
    "seed.category.subscriptions": "Subscriptions",
    "seed.category.gifts": "Gifts",
    "seed.category.hobbies": "Hobbies",
    "seed.group.non_monthly": "Non-Monthly",
    "seed.category.car_maintenance": "Car Maintenance",
    "seed.category.home_maintenance": "Home Maintenance",
    "seed.category.annual_fees": "Annual Fees",
}

#: The starter tree, by id, in the order it is seeded.
TREE: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("seed.group.income", ("seed.category.salary", "seed.category.other_income")),
    (
        "seed.group.bills",
        (
            "seed.category.rent_mortgage",
            "seed.category.electricity",
            "seed.category.water",
            "seed.category.internet",
            "seed.category.phone",
            "seed.category.insurance",
        ),
    ),
    (
        "seed.group.everyday",
        (
            "seed.category.groceries",
            "seed.category.eating_out",
            "seed.category.transport",
            "seed.category.household",
            "seed.category.health",
        ),
    ),
    (
        "seed.group.quality_of_life",
        (
            "seed.category.travel",
            "seed.category.subscriptions",
            "seed.category.gifts",
            "seed.category.hobbies",
        ),
    ),
    (
        "seed.group.non_monthly",
        (
            "seed.category.car_maintenance",
            "seed.category.home_maintenance",
            "seed.category.annual_fees",
        ),
    ),
)


def load_catalog() -> dict[str, dict[str, str]]:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


_catalog: dict[str, dict[str, str]] | None = None


def catalog() -> dict[str, dict[str, str]]:
    global _catalog
    if _catalog is None:
        _catalog = load_catalog()
    return _catalog


def resolve(locale: str | None) -> str | None:
    """The catalog locale to seed from, or None for English.

    Exact first, then the language alone (``pt-PT`` takes ``pt-BR``), the same
    rule the client negotiates by. Only a locale holding reviewed words counts.
    """
    if not locale or not LOCALE_TAG.fullmatch(locale):
        return None
    held = {one: words for one, words in catalog().items() if words}
    for one in held:
        if one.lower() == locale.lower():
            return one
    language = locale.split("-")[0].lower()
    for one in held:
        if one.split("-")[0].lower() == language:
            return one
    return None


def word(message_id: str, locale: str | None = None) -> str:
    """One seeded word in ``locale``, or in English where it has none."""
    chosen = resolve(locale)
    if chosen is not None:
        translated = catalog()[chosen].get(message_id)
        if translated:
            return translated
    return ENGLISH[message_id]


def translations(message_id: str) -> list[str]:
    """Every reviewed translation of one word, in every locale, English left out."""
    return sorted(
        {words[message_id] for words in catalog().values() if words.get(message_id)}
        - {ENGLISH[message_id]}
    )
