"""initial schema

Reversible: lossy -- everything. This is the initial schema; down is an empty database.

Revision ID: 294b483de973
Revises: 
Create Date: 2026-09-17 19:59:49.517551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '294b483de973'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('date_format', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_table('instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('configured_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance'))
    )
    op.create_table('login_attempts',
    sa.Column('email_canonical', sa.String(length=254), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_email_at', ['email_canonical', 'at'], unique=False)
        batch_op.create_index('ix_login_attempts_ip_at', ['ip', 'at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_canonical', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('totp_secret', sa.LargeBinary(), nullable=False),
    sa.Column('totp_last_counter', sa.Integer(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email_canonical'), ['email_canonical'], unique=True)

    op.create_table('accounts',
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_accounts_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_accounts_household_name', ['household_id', 'name'], unique=False)

    op.create_table('batches',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('household_id', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('undone_by_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_batches_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_batches_household_id_households'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['undone_by_id'], ['batches.id'], name=op.f('fk_batches_undone_by_id_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_batches_household_started', ['household_id', 'started_at'], unique=False)

    op.create_table('household_members',
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('added_by_id', sa.String(length=32), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_household_members_added_by_id_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_members_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_members')),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_household_members_pair')
    )
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_members_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_members_user_id'), ['user_id'], unique=False)

    op.create_table('recovery_codes',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_codes'))
    )
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_codes_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_hash', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('trusted_devices',
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trusted_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_hash', name=op.f('pk_trusted_devices'))
    )
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trusted_devices_user_id'), ['user_id'], unique=False)

    op.create_table('changes',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('household_id', sa.String(length=32), nullable=True),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('row_id', sa.String(length=32), nullable=False),
    sa.Column('op', sa.String(length=8), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('redacted', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_changes_batch_id_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_changes'))
    )
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changes_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_changes_row_history', ['table_name', 'row_id', 'seq'], unique=False)

    op.create_table('import_lines',
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_import_lines_batch_id_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_lines'))
    )
    with op.batch_alter_table('import_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_lines_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_import_lines_batch_line', ['batch_id', 'line_no'], unique=False)

    op.create_table('payees',
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_folded', sa.String(length=200), nullable=False),
    sa.Column('transfer_account_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_payees_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['accounts.id'], name=op.f('fk_payees_transfer_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payees')),
    sa.UniqueConstraint('household_id', 'name_folded', name='uq_payees_household_folded')
    )
    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payees_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payees_name_folded'), ['name_folded'], unique=False)

    op.create_table('payee_rules',
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('pattern', sa.String(length=300), nullable=False),
    sa.Column('payee_id', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_payee_rules_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], name=op.f('fk_payee_rules_payee_id_payees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payee_rules'))
    )
    with op.batch_alter_table('payee_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payee_rules_household_id'), ['household_id'], unique=False)

    op.create_table('transactions',
    sa.Column('household_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.String(length=32), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('cleared', sa.String(length=16), nullable=False),
    sa.Column('transfer_account_id', sa.String(length=32), nullable=True),
    sa.Column('transfer_transaction_id', sa.String(length=32), nullable=True),
    sa.Column('transfer_fx_rate', sa.String(length=40), nullable=True),
    sa.Column('import_id', sa.String(length=64), nullable=True),
    sa.Column('import_payee_original', sa.String(length=300), nullable=True),
    sa.Column('import_source', sa.String(length=60), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_transactions_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], name=op.f('fk_transactions_payee_id_payees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['accounts.id'], name=op.f('fk_transactions_transfer_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_transaction_id'], ['transactions.id'], name=op.f('fk_transactions_transfer_transaction_id_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('account_id', 'import_id', name='uq_transactions_account_import')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_date', ['account_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index('ix_transactions_household_date', ['household_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transfer_transaction_id'), ['transfer_transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transfer_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_import_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_household_id'))
        batch_op.drop_index('ix_transactions_household_date')
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))
        batch_op.drop_index('ix_transactions_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('payee_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payee_rules_household_id'))

    op.drop_table('payee_rules')
    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payees_name_folded'))
        batch_op.drop_index(batch_op.f('ix_payees_household_id'))

    op.drop_table('payees')
    with op.batch_alter_table('import_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_import_lines_batch_line')
        batch_op.drop_index(batch_op.f('ix_import_lines_batch_id'))

    op.drop_table('import_lines')
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.drop_index('ix_changes_row_history')
        batch_op.drop_index(batch_op.f('ix_changes_household_id'))
        batch_op.drop_index(batch_op.f('ix_changes_batch_id'))

    op.drop_table('changes')
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusted_devices_user_id'))

    op.drop_table('trusted_devices')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_codes_user_id'))

    op.drop_table('recovery_codes')
    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_household_members_household_id'))

    op.drop_table('household_members')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index('ix_batches_household_started')
        batch_op.drop_index(batch_op.f('ix_batches_household_id'))
        batch_op.drop_index(batch_op.f('ix_batches_actor_id'))

    op.drop_table('batches')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_household_name')
        batch_op.drop_index(batch_op.f('ix_accounts_household_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_canonical'))

    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_ip_at')
        batch_op.drop_index('ix_login_attempts_email_at')

    op.drop_table('login_attempts')
    op.drop_table('instance')
    op.drop_table('households')
    # ### end Alembic commands ###
