"""restrict the cascades the audit log cannot see

Reversible: clean -- foreign-key actions only. No row is read or written.

Revision ID: 3fcef1c42699
Revises: 237efd6ffffb
Create Date: 2026-09-17 21:57:16.466673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcef1c42699'
down_revision: Union[str, Sequence[str], None] = '237efd6ffffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payees_transfer_account_id_accounts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payees_transfer_account_id_accounts'), 'accounts', ['transfer_account_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_transfer_account_id_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_household_id_households'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_transfer_account_id_accounts'), 'accounts', ['transfer_account_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_household_id_households'), 'households', ['household_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_household_id_households'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_transfer_account_id_accounts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_household_id_households'), 'households', ['household_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_transfer_account_id_accounts'), 'accounts', ['transfer_account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payees_transfer_account_id_accounts'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payees_transfer_account_id_accounts'), 'accounts', ['transfer_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
