"""the audit log is written in batches, and two reads get the index they need

`changes.seq` is generated by the database, and SQLAlchemy will only read a
server-generated key back from a many-row `INSERT ... RETURNING` when every
row also carries a value of its own to match the answers against. Without one
it sent one INSERT per change row: 11,202 of them for a 10k-row one-time
import, 10,830 for its undo (#229). `_sentinel` is that value. It is nullable,
nothing reads it, and existing rows keep NULL. `ALTER TABLE ... ADD COLUMN` of
a nullable column with no default changes only SQLite's schema record: the log
is not copied, however long it is. The downgrade does copy it.

Two indexes (#238), neither of which reads or writes a row of the ledger:

- `ix_changes_household_table_row` -- a household's log of one table, by op
  and row. The members list's "transactions entered" read every transaction
  change on the instance through `ix_changes_row_history`, whose only usable
  prefix was the table name.
- `ix_import_lines_transaction_id` -- the transaction panel's "where did this
  come from" scanned every staged line ever kept.

The review also proposed a partial `ix_transactions_flow` for the flow
reports. With statistics the planner still preferred the transfer id index
over it, so the report's query says how likely its NULL tests are instead
(`reporting.flow_rows`), and no index is added for it.

Building them reads each table once; neither copies a table.

Reversible: clean -- downgrading drops a column nothing reads and two indexes, and loses nothing.

Revision ID: 89c099d8239c
Revises: a4c7e19d2b86
Create Date: 2026-10-01 10:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89c099d8239c"
down_revision: str | Sequence[str] | None = "a4c7e19d2b86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("changes", sa.Column("_sentinel", sa.Integer(), nullable=True))
    op.create_index(
        "ix_changes_household_table_row",
        "changes",
        ["household_id", "table_name", "op", "row_id", "seq"],
    )
    op.create_index(
        op.f("ix_import_lines_transaction_id"), "import_lines", ["transaction_id"]
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_import_lines_transaction_id"), table_name="import_lines")
    op.drop_index("ix_changes_household_table_row", table_name="changes")
    with op.batch_alter_table("changes", schema=None) as batch_op:
        batch_op.drop_column("_sentinel")
