"""pending sign-ins

Reversible: clean -- sign-ins in flight. Anyone affected signs in again.

Revision ID: 90265808d207
Revises: 3fcef1c42699
Create Date: 2026-09-18 03:06:10.908362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90265808d207'
down_revision: Union[str, Sequence[str], None] = '3fcef1c42699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_sign_ins',
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_sign_ins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_hash', name=op.f('pk_pending_sign_ins'))
    )
    with op.batch_alter_table('pending_sign_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_sign_ins_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_sign_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_sign_ins_user_id'))

    op.drop_table('pending_sign_ins')
    # ### end Alembic commands ###
